BD = [
    {
        "TITULO": "The Witcher 3: Wild Hunt",
        "GENERO": [
            {"NOME": "RPG", "GRAU": 10}, 
            {"NOME": "Ação", "GRAU": 9}, 
            {"NOME": "Luta", "GRAU": 5}, 
            {"NOME": "Aventura", "GRAU": 10}
        ],
        "DESENVOLVEDORA": "CD Projekt Red",
        "PLATAFORMAS": ["PlayStation 4", "Xbox One", "PC"],
        "LANCAMENTO": 2015,
        "AVALIACAO": 9.8,
        "PRECO": 59.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "The Legend of Zelda: Breath of the Wild",
        "GENERO": [
            {"NOME": "Ação", "GRAU": 9}, 
            {"NOME": "Aventura", "GRAU": 9},
            {"NOME": "Quebra-cabeça", "GRAU": 4},
            {"NOME": "Sandbox", "GRAU": 7},
            {"NOME": "Estratégia", "GRAU": 5}
        ],
        "DESENVOLVEDORA": "Nintendo",
        "PLATAFORMAS": ["Nintendo Switch", "Wii U"],
        "LANCAMENTO": 2017,
        "AVALIACAO": 9.7,
        "PRECO": 49.99,
        "FAIXA_ETARIA": "Livre",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Grand Theft Auto V",
        "GENERO": [
            {"NOME": "Ação", "GRAU": 10}, 
            {"NOME": "Mundo Aberto", "GRAU": 10}, 
            {"NOME": "Sandbox", "GRAU": 5}, 
            {"NOME": "Multijogador", "GRAU": 10}
        ],
        "DESENVOLVEDORA": "Rockstar Games",
        "PLATAFORMAS": ["PlayStation 4", "Xbox One", "PC"],
        "LANCAMENTO": 2013,
        "AVALIACAO": 9.5,
        "PRECO": 29.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Minecraft",
        "GENERO": [
            {"NOME": "Sandbox", "GRAU": 9},
            {"NOME": "Sobrevivência", "GRAU": 10},
            {"NOME": "Ação", "GRAU": 5},
            {"NOME": "Mundo Aberto", "GRAU": 10},
        ],
        "DESENVOLVEDORA": "Mojang",
        "PLATAFORMAS": [
            "PC",
            "PlayStation 4",
            "Xbox One",
            "Nintendo Switch",
            "iOS",
            "Android",
        ],
        "LANCAMENTO": 2011,
        "AVALIACAO": 9.2,
        "PRECO": 26.95,
        "FAIXA_ETARIA": "Livre",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Red Dead Redemption 2",
        "GENERO": [
            {"NOME": "Ação", "GRAU": 9}, 
            {"NOME": "Aventura", "GRAU": 9},
            {"NOME": "Mundo Aberto", "GRAU": 10},
            {"NOME": "Aventura", "GRAU": 9},
        ],
        "DESENVOLVEDORA": "Rockstar Games",
        "PLATAFORMAS": ["PlayStation 4", "Xbox One", "PC", "Google Stadia"],
        "LANCAMENTO": 2018,
        "AVALIACAO": 9.8,
        "PRECO": 59.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Fortnite",
        "GENERO": [
            {"NOME": "Battle Royale", "GRAU": 9}, 
            {"NOME": "Ação", "GRAU": 8}, 
            {"NOME": "Multijogador", "GRAU": 9},
            {"NOME": "Tiro", "GRAU": 10},
            {"NOME": "Festa", "GRAU": 10}
        ],
        "DESENVOLVEDORA": "Epic Games",
        "PLATAFORMAS": [
            "PlayStation 4",
            "Xbox One",
            "PC",
            "Nintendo Switch",
            "iOS",
            "Android",
        ],
        "LANCAMENTO": 2017,
        "AVALIACAO": 8.9,
        "PRECO": 0.00,
        "FAIXA_ETARIA": "Para adolescentes",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Cyberpunk 2077",
        "GENERO": [
            {"NOME": "RPG", "GRAU": 8}, 
            {"NOME": "Ação", "GRAU": 10},
            {"NOME": "Mundo Aberto", "GRAU": 10},
            {"NOME": "Luta", "GRAU": 7},
            {"NOME": "Tiro", "GRAU": 8},
        ],
        "DESENVOLVEDORA": "CD Projekt Red",
        "PLATAFORMAS": [
            "PlayStation 4",
            "PlayStation 5",
            "Xbox One",
            "Xbox Series X/S",
            "PC",
        ],
        "LANCAMENTO": 2020,
        "AVALIACAO": 7.2,
        "PRECO": 49.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Assassin's Creed Valhalla",
        "GENERO": [
            {"NOME": "Ação", "GRAU": 9}, 
            {"NOME": "Aventura", "GRAU": 8},
            {"NOME": "Luta", "GRAU": 10},
            {"NOME": "Mundo Aberto", "GRAU": 9},
        ],
        "DESENVOLVEDORA": "Ubisoft Montreal",
        "PLATAFORMAS": [
            "PlayStation 4",
            "PlayStation 5",
            "Xbox One",
            "Xbox Series X/S",
            "PC",
        ],
        "LANCAMENTO": 2020,
        "AVALIACAO": 9.0,
        "PRECO": 59.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Among Us",
        "GENERO": [
            {"NOME": "Festa", "GRAU": 8}, 
            {"NOME": "Multijogador", "GRAU": 8},
            {"NOME": "Sobrevivência", "GRAU": 6},
            {"NOME": "Estratégia", "GRAU": 8}
        ],
        "DESENVOLVEDORA": "InnerSloth",
        "PLATAFORMAS": ["PC", "iOS", "Android"],
        "LANCAMENTO": 2018,
        "AVALIACAO": 9.0,
        "PRECO": 0.00,
        "FAIXA_ETARIA": "Para adolescentes",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Animal Crossing: New Horizons",
        "GENERO": [
            {"NOME": "Simulação", "GRAU": 9},
            {"NOME": "Vida virtual", "GRAU": 9},
            {"NOME": "Mundo Aberto", "GRAU": 5},
            {"NOME": "Multijogador", "GRAU": 6},
        ],
        "DESENVOLVEDORA": "Nintendo",
        "PLATAFORMAS": ["Nintendo Switch"],
        "LANCAMENTO": 2020,
        "AVALIACAO": 9.5,
        "PRECO": 49.99,
        "FAIXA_ETARIA": "Para todos a partir de 10 anos",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Rainbow Six Siege",
        "GENERO": [
            {"NOME": "Tiro", "GRAU": 10}, 
            {"NOME": "Estratégia", "GRAU": 8},
            {"NOME": "Multijogador", "GRAU": 10},
            {"NOME": "Ação", "GRAU": 10}
        ],
        "DESENVOLVEDORA": "Ubisoft",
        "PLATAFORMAS": ["PlayStation 4", "Xbox One", "PC"],
        "LANCAMENTO": 2015,
        "AVALIACAO": 8.9,
        "PRECO": 29.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Death Stranding",
        "GENERO": [
            {"NOME": "Simulação", "GRAU": 10}, 
            {"NOME": "Aventura", "GRAU": 8},
            {"NOME": "Sobrevivência", "GRAU": 9},
            {"NOME": "Mundo Aberto", "GRAU": 8},

        ],
        "DESENVOLVEDORA": "Kojima Productions",
        "PLATAFORMAS": ["PlayStation 4", "PC"],
        "LANCAMENTO": 2019,
        "AVALIACAO": 8.5,
        "PRECO": 39.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Final Fantasy VII Remake",
        "GENERO": [
            {"NOME": "RPG", "GRAU": 9},
            {"NOME": "Ação", "GRAU": 9},
            {"NOME": "Aventura", "GRAU": 10},
        ],
        "DESENVOLVEDORA": "Square Enix",
        "PLATAFORMAS": ["PlayStation 4"],
        "LANCAMENTO": 2020,
        "AVALIACAO": 9.0,
        "PRECO": 49.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "The Last of Us Remastered",
        "GENERO": [
            {"NOME": "Ação", "GRAU": 9}, 
            {"NOME": "Aventura", "GRAU": 9},
            {"NOME": "Suspense", "GRAU": 10},
        ],
        "DESENVOLVEDORA": "Naughty Dog",
        "PLATAFORMAS": ["PlayStation 4"],
        "LANCAMENTO": 2014,
        "AVALIACAO": 9.5,
        "PRECO": 19.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Bloodborne",
        "GENERO": [
            {"NOME": "RPG", "GRAU": 9}, 
            {"NOME": "Ação", "GRAU": 9},
            {"NOME": "Suspense", "GRAU": 6},
            {"NOME": "Aventura", "GRAU": 6}
        ],
        "DESENVOLVEDORA": "FromSoftware",
        "PLATAFORMAS": ["PlayStation 4"],
        "LANCAMENTO": 2015,
        "AVALIACAO": 9.3,
        "PRECO": 19.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Super Smash Bros. Ultimate",
        "GENERO": [
            {"NOME": "Luta", "GRAU": 9},
            {"NOME": "Ação", "GRAU": 9},
            {"NOME": "Festa", "GRAU": 10},
            {"NOME": "Multijogador", "GRAU": 10}
        ],
        "DESENVOLVEDORA": "Bandai Namco Studios",
        "PLATAFORMAS": ["Nintendo Switch"],
        "LANCAMENTO": 2018,
        "AVALIACAO": 9.7,
        "PRECO": 59.99,
        "FAIXA_ETARIA": "Para todos a partir de 10 anos",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Persona 5 Strikers",
        "GENERO": [
            {"NOME": "RPG", "GRAU": 8}, 
            {"NOME": "Ação", "GRAU": 8}
        ],
        "DESENVOLVEDORA": "Omega Force",
        "PLATAFORMAS": ["PlayStation 4", "Nintendo Switch", "PC"],
        "LANCAMENTO": 2021,
        "AVALIACAO": 8.7,
        "PRECO": 59.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Hades",
        "GENERO": [
            {"NOME": "Roguelike", "GRAU": 9}, 
            {"NOME": "Ação", "GRAU": 9},
            {"NOME": "Estratégia", "GRAU": 9}
        ],
        "DESENVOLVEDORA": "Supergiant Games",
        "PLATAFORMAS": ["PC", "Nintendo Switch"],
        "LANCAMENTO": 2020,
        "AVALIACAO": 9.5,
        "PRECO": 24.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Monster Hunter: World",
        "GENERO": [
            {"NOME": "Ação", "GRAU": 9}, 
            {"NOME": "RPG", "GRAU": 9},
            {"NOME": "Sobrevivência", "GRAU": 10},  
        ],
        "DESENVOLVEDORA": "Capcom",
        "PLATAFORMAS": ["PlayStation 4", "Xbox One", "PC"],
        "LANCAMENTO": 2018,
        "AVALIACAO": 9.2,
        "PRECO": 29.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Sekiro: Shadows Die Twice",
        "GENERO": [
            {"NOME": "Ação", "GRAU": 9}, 
            {"NOME": "Aventura", "GRAU": 9}
        ],
        "DESENVOLVEDORA": "FromSoftware",
        "PLATAFORMAS": ["PlayStation 4", "Xbox One", "PC"],
        "LANCAMENTO": 2019,
        "AVALIACAO": 9.5,
        "PRECO": 39.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Celeste",
        "GENERO": [
            {"NOME": "Plataforma", "GRAU": 9}, 
            {"NOME": "Ação", "GRAU": 9},
            {"NOME": "Casual", "GRAU": 10},
        ],
        "DESENVOLVEDORA": "Maddy Makes Games",
        "PLATAFORMAS": ["PC", "PlayStation 4", "Xbox One", "Nintendo Switch"],
        "LANCAMENTO": 2018,
        "AVALIACAO": 9.2,
        "PRECO": 19.99,
        "FAIXA_ETARIA": "Para todos a partir de 10 anos",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "The Elder Scrolls V: Skyrim",
        "GENERO": [
            {"NOME": "RPG", "GRAU": 9}, 
            {"NOME": "Ação", "GRAU": 9},
            {"NOME": "Multijogador", "GRAU": 5},
            {"NOME": "Sobrevivência", "GRAU": 6}
        ],
        "DESENVOLVEDORA": "Bethesda Game Studios",
        "PLATAFORMAS": ["PlayStation 4", "Xbox One", "PC", "Nintendo Switch"],
        "LANCAMENTO": 2011,
        "AVALIACAO": 9.3,
        "PRECO": 39.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Outer Wilds",
        "GENERO": [
            {"NOME": "Aventura", "GRAU": 9},
            {"NOME": "Quebra-cabeça", "GRAU": 8},
            {"NOME": "Estratégia", "GRAU": 5},
            {"NOME": "Ação", "GRAU": 5},
        ],
        "DESENVOLVEDORA": "Mobius Digital",
        "PLATAFORMAS": ["PC", "PlayStation 4", "Xbox One"],
        "LANCAMENTO": 2019,
        "AVALIACAO": 9.0,
        "PRECO": 24.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Stardew Valley",
        "GENERO": [
            {"NOME": "Simulação", "GRAU": 9},
            {"NOME": "RPG", "GRAU": 9},
            {"NOME": "Multijogador", "GRAU": 10},
        ],
        "DESENVOLVEDORA": "ConcernedApe",
        "PLATAFORMAS": [
            "PC",
            "PlayStation 4",
            "Xbox One",
            "Nintendo Switch",
            "iOS",
            "Android",
        ],
        "LANCAMENTO": 2016,
        "AVALIACAO": 9.5,
        "PRECO": 14.99,
        "FAIXA_ETARIA": "Para todos a partir de 10 anos",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Divinity: Original Sin 2",
        "GENERO": [
            {"NOME": "RPG", "GRAU": 10}, 
            {"NOME": "Aventura", "GRAU": 9},
            {"NOME": "Roguelike", "GRAU": 5}, 
            {"NOME": "Ação", "GRAU": 4}
        ],
        "DESENVOLVEDORA": "Larian Studios",
        "PLATAFORMAS": ["PC", "PlayStation 4", "Xbox One", "Nintendo Switch"],
        "LANCAMENTO": 2017,
        "AVALIACAO": 9.6,
        "PRECO": 44.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Undertale",
        "GENERO": [
            {"NOME": "RPG", "GRAU": 9}, 
            {"NOME": "Aventura", "GRAU": 8},
            {"NOME": "Estratégia", "GRAU": 9}, 
            {"NOME": "Sandbox", "GRAU": 7},
        ],
        "DESENVOLVEDORA": "Toby Fox",
        "PLATAFORMAS": [
            "PC",
            "PlayStation 4",
            "PlayStation Vita",
            "Nintendo Switch",
            "Xbox One",
        ],
        "LANCAMENTO": 2015,
        "AVALIACAO": 9.3,
        "PRECO": 9.99,
        "FAIXA_ETARIA": "Para todos a partir de 10 anos",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Dead Cells",
        "GENERO": [
            {"NOME": "Roguelike", "GRAU": 9}, 
            {"NOME": "Plataforma", "GRAU": 9},
            {"NOME": "Estratégia", "GRAU": 6},
            {"NOME": "Sandbox", "GRAU": 8},
        ],
        "DESENVOLVEDORA": "Motion Twin",
        "PLATAFORMAS": [
            "PC",
            "PlayStation 4",
            "Xbox One",
            "Nintendo Switch",
            "iOS",
            "Android",
        ],
        "LANCAMENTO": 2018,
        "AVALIACAO": 9.0,
        "PRECO": 24.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Hollow Knight",
        "GENERO": [
            {"NOME": "Metroidvania", "GRAU": 10}, 
            {"NOME": "Ação", "GRAU": 7},
            {"NOME": "Estratégia", "GRAU": 6},
            {"NOME": "Sandbox", "GRAU": 8},
        ],
        "DESENVOLVEDORA": "Team Cherry",
        "PLATAFORMAS": ["PC", "PlayStation 4", "Xbox One", "Nintendo Switch"],
        "LANCAMENTO": 2017,
        "AVALIACAO": 9.4,
        "PRECO": 14.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Cuphead",
        "GENERO": [
            {"NOME": "Run and gun", "GRAU": 10},
            {"NOME": "Plataforma", "GRAU": 10},
            {"NOME": "Ação", "GRAU": 8},
            {"NOME": "Sandbox", "GRAU": 8},
        ],
        "DESENVOLVEDORA": "Studio MDHR",
        "PLATAFORMAS": ["PC", "Xbox One", "Nintendo Switch"],
        "LANCAMENTO": 2017,
        "AVALIACAO": 9.3,
        "PRECO": 19.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
    {
        "TITULO": "Ori and the Blind Forest",
        "GENERO": [
            {"NOME": "Metroidvania", "GRAU": 9},
            {"NOME": "Aventura", "GRAU": 9},
            {"NOME": "Ação", "GRAU": 7},
            {"NOME": "Sandbox", "GRAU": 6},
        ],
        "DESENVOLVEDORA": "Moon Studios",
        "PLATAFORMAS": ["PC", "Xbox One", "Nintendo Switch"],
        "LANCAMENTO": 2015,
        "AVALIACAO": 9.1,
        "PRECO": 19.99,
        "FAIXA_ETARIA": "Adulto 17+",
        "OCORRENCIAS": 0,
        "PERCENTUAL": 0,
    },
]


def zerar_ocorrencias():
    for jogo in BD:
        jogo["OCORRENCIAS"] = 0
        jogo["PERCENTUAL"] = 0


def mostrar_generos():
    print("Gêneros disponíveis:")
    generos = set()
    for jogo in BD:
        for genero in jogo["GENERO"]:
            generos.add(genero["NOME"])
    for genero in generos:
        print(f"- {genero}")
    print()
